#
name: Main workflow

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  main-action:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup git
        run: |
          git config --global init.defaultBranch main
          git config --global http.sslVerify "false"

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read config variables
        id: configs
        run: |
          cd configs
          source projects.configs
          echo "GIT_REPOSITORY_URL=$(echo $GIT_REPOSITORY_URL | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "CONTAINER_IMAGE_OWNER=$(echo $CONTAINER_IMAGE_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "APP_NAME=$(echo $APP_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Get metadata
        id: meta
        run: |
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F'/' '{print tolower($2)}')" >> $GITHUB_OUTPUT
          echo "REPO_VERSION=$(git describe --tags --always | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: Prepare files for create container image
        run: |
          mv app-be/main.py container
          mv app-be/requirements.txt container

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.configs.outputs.GIT_REPOSITORY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: ./container
          file: ./container/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.configs.outputs.GIT_REPOSITORY_URL }}/${{ steps.configs.outputs.CONTAINER_IMAGE_OWNER }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}
